### ISSUE TITLE
Request for Reference Material on gPCBurgersFoam Implementation

### ISSUE THREAD

**Issue by jcam77** [robertsawko/pdesoft2016-burgers-uq#1]
Dear Robert,

I am a Phd student at Lund University, and I am currently using your gPCBurgersFoam implementation as a base for exploring Intrusive Polynomial Chaos for Uncertainty Quantification in a simple case involving the Burgers equation. I would be grateful if you could share any reference materials or sources related to your implementation that might deepen my understanding.

Thank you very much for your assistance and contribution.

Best regards,

Javier I. Camacho

**Comment by robertsawko** [comment]
Hello, Javier.

Thanks for your interest.

I am going to add this to the README as I think this is useful in general. I will let you know when I've done this and put a link here.

**Comment by jcam77** [comment]
Hello Robert,

Thanks for getting back to me. I believe your approach is great for someone like me who is new to UQ.

Trying to grasp the overall concept of UQFoam is presenting a significant challenge for me.

**Comment by robertsawko** [comment]
I am assuming that [this](https://github.com/robertsawko/pdesoft2016-burgers-uq?tab=readme-ov-file#bibliography) is what you're after. I also added it to the comment section in the code.

Please take a look and let me know if you have questions. Happy to review my implementation.

**Comment by jcam77** [comment]
Thank you. I know the book, but sometime is difficult to connect dots.
I already make some updates because I got some warnings from creatFields.H file.

    Info<< "Reading viscosity nu\n" << endl;
//---------------------------------------------------------------
    // dimensionedScalar nu
    // (
    //     transportProperties.lookup("nu")
    // );
//---------------------------------------------------------------
    // Define kinematic viscosity 'nu' (read from transportProperties)
    dimensionedScalar nu
    (
        "nu",  // Name: kinematic viscosity
        dimensionSet(0, 2, -1, 0, 0, 0, 0),  // Units: m²/s
        transportProperties  // Read from dictionary
    );

/*

Thank you for your support.

Javier

**Comment by jcam77** [comment]
Hi Robert,

I am working on a small project that will also provide visibility to your implementation and may involve some modifications or potential upgrades. The project is titled, **“Implementation of Intrusive Polynomial Chaos for Uncertainty Quantification in Nonlinear PDEs Using gPCBurgersFoam: A Tutorial and Implementation Guide.”**

An opportunity is available for you to take part as a peer reviewer if you are interested. Please tell me if this is something you would enjoy doing. My goal is to finish the project before Christmas, so hopefully I will have something interesting to share by then.

Could you let me know how you would like to be cited?

Regards

Javier

**Comment by robertsawko** [comment]
Hi Javier,

I am a bit snowed under. Occasional technical support with the code in this repository I am happy to help out via Github Issues, but reviewing any technical writing or other content is probably beyond my time limits right now.

**Comment by jcam77** [comment]
Hi Robert,

If you don’t have the time, that’s totally fine. I just wanted to give you the opportunity to decide if you’d like to take part in the review.
